// Centralized Element Plus style imports. Add new component styles here when adopting more Element Plus widgets.
import 'element-plus/theme-chalk/dark/css-vars.css'
import 'element-plus/es/components/button/style/css'
import 'element-plus/es/components/form/style/css'
import 'element-plus/es/components/input/style/css'
import 'element-plus/es/components/input-number/style/css'
import 'element-plus/es/components/option/style/css'
import 'element-plus/es/components/select/style/css'
import 'element-plus/es/components/switch/style/css'
import './element-plus-overrides.css'
